AWSTemplateFormatVersion: '2010-09-09'
Description: 'Networking Infrastructure for E-Commerce Platform'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: E-Commerce-VPC
