AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CodePipeline for deploying service-1'

Resources:
  CodePipelineService1:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole'
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactStoreS3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                RepositoryName: !Ref CodeCommitRepositoryName
                BranchName: main
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ApplicationName: !Ref CodeDeployApplicationName
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
              RunOrder: 1

Parameters:
  CodeCommitRepositoryName:
    Type: String
    Description: The name of the CodeCommit repository for the source stage.
  CodeBuildProjectName:
    Type: String
    Description: The name of the CodeBuild project for the build stage.
  CodeDeployApplicationName:
    Type: String
    Description: The name of the CodeDeploy application for the deploy stage.
  CodeDeployDeploymentGroup:
    Type: String
    Description: The deployment group in CodeDeploy.
  CodePipelineArtifactStoreS3Bucket:
    Type: String
    Description: The S3 bucket for storing pipeline artifacts.

Outputs:
  CodePipelineName:
    Description: The name of the CodePipeline
    Value: !Ref CodePipelineService1
